"""initial schema

Revision ID: 6c6ead28332d
Revises:
Create Date: 2026-07-13 05:26:53.700990+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

revision: str = "6c6ead28332d"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "site",
        sa.Column("pk", sa.Integer(), nullable=False),
        sa.Column("family", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("code", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("articlepath", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("host", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("api_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("label", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("pk"),
        sa.UniqueConstraint("family", "code", name="uq_site_family_code"),
        if_not_exists=True,
    )
    op.create_table(
        "fetchrequest",
        sa.Column("pk", sa.Integer(), nullable=False),
        sa.Column("site_pk", sa.Integer(), nullable=False),
        sa.Column("parent_pk", sa.Integer(), nullable=True),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("single", "index", "page", "transclusion", name="fetchkind"),
            nullable=False,
        ),
        sa.Column("depth", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "in_progress",
                "done",
                "error",
                "cancelled",
                name="fetchstatus",
            ),
            nullable=False,
        ),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("progress_done", sa.Integer(), nullable=False),
        sa.Column("progress_total", sa.Integer(), nullable=True),
        sa.Column("error_message", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("requested_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_pk"],
            ["fetchrequest.pk"],
        ),
        sa.ForeignKeyConstraint(
            ["site_pk"],
            ["site.pk"],
        ),
        sa.PrimaryKeyConstraint("pk"),
        if_not_exists=True,
    )
    op.create_index(
        op.f("ix_fetchrequest_status"),
        "fetchrequest",
        ["status"],
        unique=False,
        if_not_exists=True,
    )

    op.create_table(
        "namespace",
        sa.Column("pk", sa.Integer(), nullable=False),
        sa.Column("site_pk", sa.Integer(), nullable=False),
        sa.Column("key", sa.Integer(), nullable=False),
        sa.Column("canonical_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("local_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "main",
                "page",
                "index",
                "file",
                "template",
                "module",
                "category",
                "author",
                "book",
                "other",
                name="nsrole",
            ),
            nullable=False,
        ),
        sa.Column("subpages", sa.Boolean(), nullable=False),
        sa.Column("content", sa.Boolean(), nullable=False),
        sa.Column("case", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["site_pk"],
            ["site.pk"],
        ),
        sa.PrimaryKeyConstraint("pk"),
        sa.UniqueConstraint("site_pk", "key", name="uq_ns_site_key"),
        if_not_exists=True,
    )
    op.create_table(
        "page",
        sa.Column("pk", sa.Integer(), nullable=False),
        sa.Column("site_pk", sa.Integer(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "namespace_role",
            sa.Enum(
                "main",
                "page",
                "index",
                "file",
                "template",
                "module",
                "category",
                "author",
                "book",
                "other",
                name="nsrole",
            ),
            nullable=False,
        ),
        sa.Column("namespace_key", sa.Integer(), nullable=True),
        sa.Column("content_model", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("pageid", sa.Integer(), nullable=True),
        sa.Column("revid", sa.Integer(), nullable=True),
        sa.Column("remote_timestamp", sa.DateTime(), nullable=True),
        sa.Column("contributor", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("comment", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("sha1", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("text", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("local_modified_at", sa.DateTime(), nullable=True),
        sa.Column("dirty", sa.Boolean(), nullable=False),
        sa.Column(
            "fetch_status",
            sa.Enum(
                "unfetched", "pending", "fetching", "done", "error", name="fetchstate"
            ),
            nullable=False,
        ),
        sa.Column("fetch_error", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["site_pk"],
            ["site.pk"],
        ),
        sa.PrimaryKeyConstraint("pk"),
        sa.UniqueConstraint("site_pk", "title", name="uq_page_site_title"),
        if_not_exists=True,
    )
    op.create_index(
        op.f("ix_page_dirty"),
        "page",
        ["dirty"],
        unique=False,
        if_not_exists=True,
    )

    op.create_table(
        "sitecredential",
        sa.Column("site_pk", sa.Integer(), nullable=False),
        sa.Column("username", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("bot_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("password", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["site_pk"],
            ["site.pk"],
        ),
        sa.PrimaryKeyConstraint("site_pk"),
        if_not_exists=True,
    )
    op.create_table(
        "annotationanchor",
        sa.Column("pk", sa.Integer(), nullable=False),
        sa.Column("page_pk", sa.Integer(), nullable=False),
        sa.Column("annotation_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("text_start", sa.Integer(), nullable=False),
        sa.Column("text_end", sa.Integer(), nullable=False),
        sa.Column("anchor_revid", sa.Integer(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["page_pk"],
            ["page.pk"],
        ),
        sa.PrimaryKeyConstraint("pk"),
        sa.UniqueConstraint(
            "page_pk", "annotation_id", name="uq_anchor_page_annotation"
        ),
        if_not_exists=True,
    )
    op.create_index(
        op.f("ix_annotationanchor_annotation_id"),
        "annotationanchor",
        ["annotation_id"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        op.f("ix_annotationanchor_page_pk"),
        "annotationanchor",
        ["page_pk"],
        unique=False,
        if_not_exists=True,
    )

    op.create_table(
        "commit",
        sa.Column("pk", sa.Integer(), nullable=False),
        sa.Column("page_pk", sa.Integer(), nullable=False),
        sa.Column("base_revid", sa.Integer(), nullable=True),
        sa.Column("submitted_body", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("comment", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("pending", "success", "conflict", "error", name="commitstatus"),
            nullable=False,
        ),
        sa.Column("result_revid", sa.Integer(), nullable=True),
        sa.Column("error_message", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["page_pk"],
            ["page.pk"],
        ),
        sa.PrimaryKeyConstraint("pk"),
        if_not_exists=True,
    )
    op.create_index(
        op.f("ix_commit_page_pk"),
        "commit",
        ["page_pk"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        op.f("ix_commit_status"),
        "commit",
        ["status"],
        unique=False,
        if_not_exists=True,
    )

    op.create_table(
        "editjournal",
        sa.Column("pk", sa.Integer(), nullable=False),
        sa.Column("page_pk", sa.Integer(), nullable=False),
        sa.Column("base_revid", sa.Integer(), nullable=True),
        sa.Column("body", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("comment", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("saved_at", sa.DateTime(), nullable=False),
        sa.Column("committed", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["page_pk"],
            ["page.pk"],
        ),
        sa.PrimaryKeyConstraint("pk"),
        if_not_exists=True,
    )
    op.create_index(
        op.f("ix_editjournal_committed"),
        "editjournal",
        ["committed"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        op.f("ix_editjournal_page_pk"),
        "editjournal",
        ["page_pk"],
        unique=False,
        if_not_exists=True,
    )

    op.create_table(
        "fileblob",
        sa.Column("pk", sa.Integer(), nullable=False),
        sa.Column("page_pk", sa.Integer(), nullable=False),
        sa.Column("file_sha1", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("size", sa.Integer(), nullable=True),
        sa.Column("mime", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("upload_timestamp", sa.DateTime(), nullable=True),
        sa.Column("uploader", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("upload_comment", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("local_path", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("downloaded_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["page_pk"],
            ["page.pk"],
        ),
        sa.PrimaryKeyConstraint("pk"),
        if_not_exists=True,
    )
    op.create_index(
        op.f("ix_fileblob_page_pk"),
        "fileblob",
        ["page_pk"],
        unique=False,
        if_not_exists=True,
    )

    op.create_table(
        "filemeta",
        sa.Column("pk", sa.Integer(), nullable=False),
        sa.Column("page_pk", sa.Integer(), nullable=False),
        sa.Column(
            "origin",
            sa.Enum("remote", "paste", "ocr", name="fileorigin"),
            nullable=False,
        ),
        sa.Column("source_page_pk", sa.Integer(), nullable=True),
        sa.Column("source_page_number", sa.Integer(), nullable=True),
        sa.Column("crop_x", sa.Integer(), nullable=True),
        sa.Column("crop_y", sa.Integer(), nullable=True),
        sa.Column("crop_w", sa.Integer(), nullable=True),
        sa.Column("crop_h", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["page_pk"],
            ["page.pk"],
        ),
        sa.ForeignKeyConstraint(
            ["source_page_pk"],
            ["page.pk"],
        ),
        sa.PrimaryKeyConstraint("pk"),
        sa.UniqueConstraint("page_pk", name="uq_filemeta_page"),
        if_not_exists=True,
    )
    op.create_index(
        op.f("ix_filemeta_page_pk"),
        "filemeta",
        ["page_pk"],
        unique=False,
        if_not_exists=True,
    )

    op.create_table(
        "indexmeta",
        sa.Column("pk", sa.Integer(), nullable=False),
        sa.Column("page_pk", sa.Integer(), nullable=False),
        sa.Column("site_pk", sa.Integer(), nullable=False),
        sa.Column("short_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["page_pk"],
            ["page.pk"],
        ),
        sa.ForeignKeyConstraint(
            ["site_pk"],
            ["site.pk"],
        ),
        sa.PrimaryKeyConstraint("pk"),
        sa.UniqueConstraint("page_pk", name="uq_indexmeta_page"),
        sa.UniqueConstraint("site_pk", "short_name", name="uq_indexmeta_site_short"),
        if_not_exists=True,
    )
    op.create_index(
        op.f("ix_indexmeta_page_pk"),
        "indexmeta",
        ["page_pk"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        op.f("ix_indexmeta_site_pk"),
        "indexmeta",
        ["site_pk"],
        unique=False,
        if_not_exists=True,
    )

    op.create_table(
        "pagemeta",
        sa.Column("pk", sa.Integer(), nullable=False),
        sa.Column("page_pk", sa.Integer(), nullable=False),
        sa.Column("index_title", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("page_number", sa.Integer(), nullable=True),
        sa.Column("quality_level", sa.Integer(), nullable=True),
        sa.Column(
            "source_image_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("thumb_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("thumb_width", sa.Integer(), nullable=True),
        sa.Column("thumb_height", sa.Integer(), nullable=True),
        sa.Column("raster_path", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("thumb_path", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["page_pk"],
            ["page.pk"],
        ),
        sa.PrimaryKeyConstraint("pk"),
        sa.UniqueConstraint("page_pk", name="uq_pagemeta_page"),
        if_not_exists=True,
    )
    op.create_index(
        op.f("ix_pagemeta_index_title"),
        "pagemeta",
        ["index_title"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        op.f("ix_pagemeta_page_pk"),
        "pagemeta",
        ["page_pk"],
        unique=False,
        if_not_exists=True,
    )

    op.create_table(
        "transclusion",
        sa.Column("pk", sa.Integer(), nullable=False),
        sa.Column("site_pk", sa.Integer(), nullable=False),
        sa.Column("source_page_pk", sa.Integer(), nullable=False),
        sa.Column("index_title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("from_page", sa.Integer(), nullable=False),
        sa.Column("to_page", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["site_pk"],
            ["site.pk"],
        ),
        sa.ForeignKeyConstraint(
            ["source_page_pk"],
            ["page.pk"],
        ),
        sa.PrimaryKeyConstraint("pk"),
        if_not_exists=True,
    )
    op.create_index(
        op.f("ix_transclusion_index_title"),
        "transclusion",
        ["index_title"],
        unique=False,
        if_not_exists=True,
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_transclusion_index_title"),
        table_name="transclusion",
        if_exists=True,
    )
    op.drop_table("transclusion", if_exists=True)
    op.drop_index(op.f("ix_pagemeta_page_pk"), table_name="pagemeta", if_exists=True)
    op.drop_index(
        op.f("ix_pagemeta_index_title"),
        table_name="pagemeta",
        if_exists=True,
    )
    op.drop_table("pagemeta", if_exists=True)
    op.drop_index(
        op.f("ix_indexmeta_site_pk"),
        table_name="indexmeta",
        if_exists=True,
    )
    op.drop_index(
        op.f("ix_indexmeta_page_pk"),
        table_name="indexmeta",
        if_exists=True,
    )
    op.drop_table("indexmeta", if_exists=True)
    op.drop_index(op.f("ix_filemeta_page_pk"), table_name="filemeta", if_exists=True)
    op.drop_table("filemeta", if_exists=True)
    op.drop_index(op.f("ix_fileblob_page_pk"), table_name="fileblob", if_exists=True)
    op.drop_table("fileblob", if_exists=True)
    op.drop_index(
        op.f("ix_editjournal_page_pk"),
        table_name="editjournal",
        if_exists=True,
    )
    op.drop_index(
        op.f("ix_editjournal_committed"),
        table_name="editjournal",
        if_exists=True,
    )
    op.drop_table("editjournal", if_exists=True)
    op.drop_index(op.f("ix_commit_status"), table_name="commit", if_exists=True)
    op.drop_index(op.f("ix_commit_page_pk"), table_name="commit", if_exists=True)
    op.drop_table("commit", if_exists=True)
    op.drop_index(
        op.f("ix_annotationanchor_page_pk"),
        table_name="annotationanchor",
        if_exists=True,
    )
    op.drop_index(
        op.f("ix_annotationanchor_annotation_id"),
        table_name="annotationanchor",
        if_exists=True,
    )
    op.drop_table("annotationanchor", if_exists=True)
    op.drop_table("sitecredential", if_exists=True)
    op.drop_index(op.f("ix_page_dirty"), table_name="page", if_exists=True)
    op.drop_table("page", if_exists=True)
    op.drop_table("namespace", if_exists=True)
    op.drop_index(
        op.f("ix_fetchrequest_status"),
        table_name="fetchrequest",
        if_exists=True,
    )
    op.drop_table("fetchrequest", if_exists=True)
    op.drop_table("site", if_exists=True)
    # ### end Alembic commands ###
