"""make annotation category non nullable

Revision ID: 76940b0f1272
Revises: c38d2e7f901a
Create Date: 2026-09-23 20:11:43.310256+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "76940b0f1272"
down_revision: str | None = "c38d2e7f901a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("scanannotation", schema=None) as batch_op:
        op.execute(sa.text("""
                           UPDATE scanannotation
                           SET category = 'unknown'
                           WHERE category IS NULL
                           """))

        batch_op.alter_column(
            "category", existing_type=sa.VARCHAR(length=9), nullable=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("scanannotation", schema=None) as batch_op:
        batch_op.alter_column(
            "category", existing_type=sa.VARCHAR(length=9), nullable=True
        )

    # ### end Alembic commands ###
