"""baseline

Revision ID: 8ac41e2d7f90
Revises:
Create Date: 2026-08-14 23:56:50.604580+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

revision: str = "8ac41e2d7f90"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "content",
        sa.Column("pk", sa.Integer(), nullable=False),
        sa.Column("content_sha1", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("comparable_sha1", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("content_model", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("text", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("remote_sha1", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("remote_size", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("pk"),
        sa.UniqueConstraint(
            "content_sha1", "content_model", name="uq_content_sha1_model"
        ),
    )
    with op.batch_alter_table("content", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_content_comparable_sha1"), ["comparable_sha1"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_content_content_sha1"), ["content_sha1"], unique=False
        )

    op.create_table(
        "indexlink",
        sa.Column("pk", sa.Integer(), nullable=False),
        sa.Column("page_link_pk", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["page_link_pk"],
            ["pagelink.pk"],
        ),
        sa.PrimaryKeyConstraint("pk"),
    )
    with op.batch_alter_table("indexlink", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_indexlink_page_link_pk"), ["page_link_pk"], unique=True
        )

    op.create_table(
        "ocrbackendconfig",
        sa.Column("pk", sa.Integer(), nullable=False),
        sa.Column("scope", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("wikimedia", "token_api", name="ocrbackendkind"),
            nullable=False,
        ),
        sa.Column("base_url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("api_token", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("default_engine", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("default_langs", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("default_prompt", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("pk"),
        sa.UniqueConstraint("scope", "name", name="uq_ocr_backend_scope_name"),
    )
    with op.batch_alter_table("ocrbackendconfig", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_ocrbackendconfig_scope"), ["scope"], unique=False
        )

    op.create_table(
        "pagelink",
        sa.Column("pk", sa.Integer(), nullable=False),
        sa.Column("local_page_pk", sa.Integer(), nullable=False),
        sa.Column("remote_page_pk", sa.Integer(), nullable=False),
        sa.Column("index_link_pk", sa.Integer(), nullable=True),
        sa.Column(
            "origin",
            sa.Enum("copy", "title_match", "manual", "reconciled", name="linkorigin"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["index_link_pk"],
            ["indexlink.pk"],
        ),
        sa.ForeignKeyConstraint(
            ["local_page_pk"],
            ["page.pk"],
        ),
        sa.ForeignKeyConstraint(
            ["remote_page_pk"],
            ["page.pk"],
        ),
        sa.PrimaryKeyConstraint("pk"),
    )
    with op.batch_alter_table("pagelink", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_pagelink_index_link_pk"), ["index_link_pk"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_pagelink_local_page_pk"), ["local_page_pk"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_pagelink_remote_page_pk"), ["remote_page_pk"], unique=False
        )

    op.execute(
        sa.text(
            "CREATE UNIQUE INDEX uq_pagelink_pair ON pagelink"
            " (min(local_page_pk, remote_page_pk),"
            " max(local_page_pk, remote_page_pk))"
        )
    )

    op.create_table(
        "site",
        sa.Column("pk", sa.Integer(), nullable=False),
        sa.Column("family", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("code", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("articlepath", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("api_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("label", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("changes_seen_through", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("pk"),
        sa.UniqueConstraint("family", "code", name="uq_site_family_code"),
        sa.UniqueConstraint("label", name="uq_site_label"),
    )
    op.create_table(
        "fetchrequest",
        sa.Column("pk", sa.Integer(), nullable=False),
        sa.Column("site_pk", sa.Integer(), nullable=False),
        sa.Column("parent_pk", sa.Integer(), nullable=True),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("single", "index", "page", "transclusion", name="fetchkind"),
            nullable=False,
        ),
        sa.Column("depth", sa.Integer(), nullable=False),
        sa.Column("revisions", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "in_progress",
                "done",
                "error",
                "cancelled",
                name="fetchstatus",
            ),
            nullable=False,
        ),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("progress_done", sa.Integer(), nullable=False),
        sa.Column("progress_total", sa.Integer(), nullable=True),
        sa.Column("error_message", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("requested_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_pk"],
            ["fetchrequest.pk"],
        ),
        sa.ForeignKeyConstraint(
            ["site_pk"],
            ["site.pk"],
        ),
        sa.PrimaryKeyConstraint("pk"),
    )
    with op.batch_alter_table("fetchrequest", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_fetchrequest_status"), ["status"], unique=False
        )

    op.create_table(
        "namespace",
        sa.Column("pk", sa.Integer(), nullable=False),
        sa.Column("site_pk", sa.Integer(), nullable=False),
        sa.Column("key", sa.Integer(), nullable=False),
        sa.Column("canonical_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("local_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "main",
                "page",
                "index",
                "file",
                "template",
                "module",
                "category",
                "author",
                "book",
                "other",
                name="nsrole",
            ),
            nullable=False,
        ),
        sa.Column("subpages", sa.Boolean(), nullable=False),
        sa.Column("content", sa.Boolean(), nullable=False),
        sa.Column("case", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["site_pk"],
            ["site.pk"],
        ),
        sa.PrimaryKeyConstraint("pk"),
        sa.UniqueConstraint("site_pk", "key", name="uq_ns_site_key"),
    )
    op.create_table(
        "page",
        sa.Column("pk", sa.Integer(), nullable=False),
        sa.Column("site_pk", sa.Integer(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "namespace_role",
            sa.Enum(
                "main",
                "page",
                "index",
                "file",
                "template",
                "module",
                "category",
                "author",
                "book",
                "other",
                name="nsrole",
            ),
            nullable=False,
        ),
        sa.Column("namespace_key", sa.Integer(), nullable=True),
        sa.Column("content_model", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("pageid", sa.Integer(), nullable=True),
        sa.Column("revid", sa.Integer(), nullable=True),
        sa.Column("remote_timestamp", sa.DateTime(), nullable=True),
        sa.Column("contributor", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("comment", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("text", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("local_modified_at", sa.DateTime(), nullable=True),
        sa.Column("dirty", sa.Boolean(), nullable=False),
        sa.Column(
            "fetch_status",
            sa.Enum(
                "unfetched", "pending", "fetching", "done", "error", name="fetchstate"
            ),
            nullable=False,
        ),
        sa.Column("fetch_error", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("latest_revision_pk", sa.Integer(), nullable=True),
        sa.Column("history_complete_from_revid", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["site_pk"],
            ["site.pk"],
        ),
        sa.PrimaryKeyConstraint("pk"),
        sa.UniqueConstraint("site_pk", "title", name="uq_page_site_title"),
    )
    with op.batch_alter_table("page", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_page_dirty"), ["dirty"], unique=False)

    op.create_table(
        "promotionbatch",
        sa.Column("pk", sa.Integer(), nullable=False),
        sa.Column("source_site_pk", sa.Integer(), nullable=False),
        sa.Column("target_site_pk", sa.Integer(), nullable=False),
        sa.Column("index_link_pk", sa.Integer(), nullable=True),
        sa.Column(
            "source_index_title", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "target_index_title", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("label", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "running",
                "complete",
                "partial",
                "aborted",
                name="batchstatus",
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["index_link_pk"],
            ["indexlink.pk"],
        ),
        sa.ForeignKeyConstraint(
            ["source_site_pk"],
            ["site.pk"],
        ),
        sa.ForeignKeyConstraint(
            ["target_site_pk"],
            ["site.pk"],
        ),
        sa.PrimaryKeyConstraint("pk"),
    )
    with op.batch_alter_table("promotionbatch", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_promotionbatch_index_link_pk"),
            ["index_link_pk"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_promotionbatch_source_site_pk"),
            ["source_site_pk"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_promotionbatch_status"), ["status"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_promotionbatch_target_site_pk"),
            ["target_site_pk"],
            unique=False,
        )

    op.create_table(
        "sitecredential",
        sa.Column("site_pk", sa.Integer(), nullable=False),
        sa.Column("username", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("bot_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("password", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["site_pk"],
            ["site.pk"],
        ),
        sa.PrimaryKeyConstraint("site_pk"),
    )
    op.create_table(
        "boxrangelink",
        sa.Column("pk", sa.Integer(), nullable=False),
        sa.Column("page_pk", sa.Integer(), nullable=False),
        sa.Column(
            "box_annotation_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "range_annotation_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["page_pk"],
            ["page.pk"],
        ),
        sa.PrimaryKeyConstraint("pk"),
        sa.UniqueConstraint(
            "page_pk", "box_annotation_id", name="uq_box_range_link_box"
        ),
    )
    with op.batch_alter_table("boxrangelink", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_boxrangelink_box_annotation_id"),
            ["box_annotation_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_boxrangelink_page_pk"), ["page_pk"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_boxrangelink_range_annotation_id"),
            ["range_annotation_id"],
            unique=False,
        )

    op.create_table(
        "commit",
        sa.Column("pk", sa.Integer(), nullable=False),
        sa.Column("page_pk", sa.Integer(), nullable=False),
        sa.Column("base_revid", sa.Integer(), nullable=True),
        sa.Column("submitted_body", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("comment", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("pending", "success", "conflict", "error", name="commitstatus"),
            nullable=False,
        ),
        sa.Column("result_revid", sa.Integer(), nullable=True),
        sa.Column("error_message", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["page_pk"],
            ["page.pk"],
        ),
        sa.PrimaryKeyConstraint("pk"),
    )
    with op.batch_alter_table("commit", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_commit_page_pk"), ["page_pk"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_commit_status"), ["status"], unique=False)

    op.create_table(
        "editjournal",
        sa.Column("pk", sa.Integer(), nullable=False),
        sa.Column("page_pk", sa.Integer(), nullable=False),
        sa.Column("base_revid", sa.Integer(), nullable=True),
        sa.Column("body", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("comment", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("saved_at", sa.DateTime(), nullable=False),
        sa.Column("committed", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["page_pk"],
            ["page.pk"],
        ),
        sa.PrimaryKeyConstraint("pk"),
    )
    with op.batch_alter_table("editjournal", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_editjournal_committed"), ["committed"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_editjournal_page_pk"), ["page_pk"], unique=False
        )

    op.create_table(
        "fileblob",
        sa.Column("pk", sa.Integer(), nullable=False),
        sa.Column("page_pk", sa.Integer(), nullable=False),
        sa.Column("file_sha1", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("size", sa.Integer(), nullable=True),
        sa.Column("mime", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("upload_timestamp", sa.DateTime(), nullable=True),
        sa.Column("uploader", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("upload_comment", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("local_path", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("downloaded_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["page_pk"],
            ["page.pk"],
        ),
        sa.PrimaryKeyConstraint("pk"),
    )
    with op.batch_alter_table("fileblob", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_fileblob_page_pk"), ["page_pk"], unique=False
        )

    op.create_table(
        "filemeta",
        sa.Column("pk", sa.Integer(), nullable=False),
        sa.Column("page_pk", sa.Integer(), nullable=False),
        sa.Column(
            "origin",
            sa.Enum("remote", "paste", "ocr", name="fileorigin"),
            nullable=False,
        ),
        sa.Column("source_page_pk", sa.Integer(), nullable=True),
        sa.Column("source_page_number", sa.Integer(), nullable=True),
        sa.Column("crop_x", sa.Integer(), nullable=True),
        sa.Column("crop_y", sa.Integer(), nullable=True),
        sa.Column("crop_w", sa.Integer(), nullable=True),
        sa.Column("crop_h", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["page_pk"],
            ["page.pk"],
        ),
        sa.ForeignKeyConstraint(
            ["source_page_pk"],
            ["page.pk"],
        ),
        sa.PrimaryKeyConstraint("pk"),
        sa.UniqueConstraint("page_pk", name="uq_filemeta_page"),
    )
    with op.batch_alter_table("filemeta", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_filemeta_page_pk"), ["page_pk"], unique=False
        )

    op.create_table(
        "indexmeta",
        sa.Column("pk", sa.Integer(), nullable=False),
        sa.Column("page_pk", sa.Integer(), nullable=False),
        sa.Column("site_pk", sa.Integer(), nullable=False),
        sa.Column("short_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["page_pk"],
            ["page.pk"],
        ),
        sa.ForeignKeyConstraint(
            ["site_pk"],
            ["site.pk"],
        ),
        sa.PrimaryKeyConstraint("pk"),
        sa.UniqueConstraint("page_pk", name="uq_indexmeta_page"),
        sa.UniqueConstraint("site_pk", "short_name", name="uq_indexmeta_site_short"),
    )
    with op.batch_alter_table("indexmeta", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_indexmeta_page_pk"), ["page_pk"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_indexmeta_site_pk"), ["site_pk"], unique=False
        )

    op.create_table(
        "proofreadpagemeta",
        sa.Column("page_pk", sa.Integer(), nullable=False),
        sa.Column("index_page_pk", sa.Integer(), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=True),
        sa.Column("quality_level", sa.Integer(), nullable=True),
        sa.Column(
            "source_image_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("default_body", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("thumb_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("thumb_width", sa.Integer(), nullable=True),
        sa.Column("thumb_height", sa.Integer(), nullable=True),
        sa.Column("raster_path", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("thumb_path", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["index_page_pk"],
            ["page.pk"],
        ),
        sa.ForeignKeyConstraint(
            ["page_pk"],
            ["page.pk"],
        ),
        sa.PrimaryKeyConstraint("page_pk"),
    )
    with op.batch_alter_table("proofreadpagemeta", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_proofreadpagemeta_index_page_pk"),
            ["index_page_pk"],
            unique=False,
        )

    op.create_table(
        "revision",
        sa.Column("pk", sa.Integer(), nullable=False),
        sa.Column("page_pk", sa.Integer(), nullable=False),
        sa.Column("revid", sa.Integer(), nullable=False),
        sa.Column("parent_revid", sa.Integer(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.Column("contributor", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("comment", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("minor", sa.Boolean(), nullable=False),
        sa.Column("observed_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["page_pk"],
            ["page.pk"],
        ),
        sa.PrimaryKeyConstraint("pk"),
        sa.UniqueConstraint("page_pk", "revid", name="uq_revision_page_revid"),
    )
    with op.batch_alter_table("revision", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_revision_page_pk"), ["page_pk"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_revision_revid"), ["revid"], unique=False)

    op.create_table(
        "scanannotation",
        sa.Column("pk", sa.Integer(), nullable=False),
        sa.Column("page_pk", sa.Integer(), nullable=False),
        sa.Column("annotation_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("x", sa.Float(), nullable=False),
        sa.Column("y", sa.Float(), nullable=False),
        sa.Column("width", sa.Float(), nullable=False),
        sa.Column("height", sa.Float(), nullable=False),
        sa.Column("label", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "category",
            sa.Enum(
                "header",
                "footer",
                "body",
                "paragraph",
                "section",
                "ignore",
                "equation",
                name="annotationcategory",
            ),
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["page_pk"],
            ["page.pk"],
        ),
        sa.PrimaryKeyConstraint("pk"),
        sa.UniqueConstraint(
            "page_pk", "annotation_id", name="uq_scan_annotation_page_annotation"
        ),
    )
    with op.batch_alter_table("scanannotation", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_scanannotation_annotation_id"),
            ["annotation_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_scanannotation_page_pk"), ["page_pk"], unique=False
        )

    op.create_table(
        "texttargetanchor",
        sa.Column("pk", sa.Integer(), nullable=False),
        sa.Column("page_pk", sa.Integer(), nullable=False),
        sa.Column("annotation_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("text_start", sa.Integer(), nullable=False),
        sa.Column("text_end", sa.Integer(), nullable=False),
        sa.Column("anchor_revid", sa.Integer(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["page_pk"],
            ["page.pk"],
        ),
        sa.PrimaryKeyConstraint("pk"),
        sa.UniqueConstraint(
            "page_pk", "annotation_id", name="uq_text_target_anchor_page_annotation"
        ),
    )
    with op.batch_alter_table("texttargetanchor", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_texttargetanchor_annotation_id"),
            ["annotation_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_texttargetanchor_page_pk"), ["page_pk"], unique=False
        )

    op.create_table(
        "transclusion",
        sa.Column("pk", sa.Integer(), nullable=False),
        sa.Column("site_pk", sa.Integer(), nullable=False),
        sa.Column("source_page_pk", sa.Integer(), nullable=False),
        sa.Column("index_title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("from_page", sa.Integer(), nullable=False),
        sa.Column("to_page", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["site_pk"],
            ["site.pk"],
        ),
        sa.ForeignKeyConstraint(
            ["source_page_pk"],
            ["page.pk"],
        ),
        sa.PrimaryKeyConstraint("pk"),
    )
    with op.batch_alter_table("transclusion", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_transclusion_index_title"), ["index_title"], unique=False
        )

    op.create_table(
        "revisionlink",
        sa.Column("pk", sa.Integer(), nullable=False),
        sa.Column("page_link_pk", sa.Integer(), nullable=True),
        sa.Column("local_revision_pk", sa.Integer(), nullable=False),
        sa.Column("remote_revision_pk", sa.Integer(), nullable=False),
        sa.Column(
            "origin",
            sa.Enum("copy", "title_match", "manual", "reconciled", name="linkorigin"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["local_revision_pk"],
            ["revision.pk"],
        ),
        sa.ForeignKeyConstraint(
            ["page_link_pk"],
            ["pagelink.pk"],
        ),
        sa.ForeignKeyConstraint(
            ["remote_revision_pk"],
            ["revision.pk"],
        ),
        sa.PrimaryKeyConstraint("pk"),
    )
    with op.batch_alter_table("revisionlink", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_revisionlink_local_revision_pk"),
            ["local_revision_pk"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_revisionlink_page_link_pk"), ["page_link_pk"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_revisionlink_remote_revision_pk"),
            ["remote_revision_pk"],
            unique=False,
        )

    op.execute(
        sa.text(
            "CREATE UNIQUE INDEX uq_revisionlink_pair ON revisionlink"
            " (min(local_revision_pk, remote_revision_pk),"
            " max(local_revision_pk, remote_revision_pk))"
        )
    )

    op.create_table(
        "slot",
        sa.Column("revision_pk", sa.Integer(), nullable=False),
        sa.Column("role", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("content_pk", sa.Integer(), nullable=False),
        sa.Column("origin_revid", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["content_pk"],
            ["content.pk"],
        ),
        sa.ForeignKeyConstraint(
            ["revision_pk"],
            ["revision.pk"],
        ),
        sa.PrimaryKeyConstraint("revision_pk", "role"),
    )
    with op.batch_alter_table("slot", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_slot_content_pk"), ["content_pk"], unique=False
        )

    op.create_table(
        "promotion",
        sa.Column("pk", sa.Integer(), nullable=False),
        sa.Column("batch_pk", sa.Integer(), nullable=False),
        sa.Column("page_link_pk", sa.Integer(), nullable=True),
        sa.Column("source_page_pk", sa.Integer(), nullable=False),
        sa.Column("target_page_pk", sa.Integer(), nullable=True),
        sa.Column("target_title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=True),
        sa.Column(
            "intent",
            sa.Enum("create", "update", name="promotionintent"),
            nullable=False,
        ),
        sa.Column("source_revision_pk", sa.Integer(), nullable=False),
        sa.Column("source_head_revid", sa.Integer(), nullable=True),
        sa.Column("predecessor_promotion_pk", sa.Integer(), nullable=True),
        sa.Column("anchor_link_pk", sa.Integer(), nullable=True),
        sa.Column("base_revid", sa.Integer(), nullable=True),
        sa.Column("body", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("comment", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "staged",
                "pushed",
                "conflict",
                "error",
                "skipped",
                name="promotionstatus",
            ),
            nullable=False,
        ),
        sa.Column("pre_push_target_revid", sa.Integer(), nullable=True),
        sa.Column("result_revid", sa.Integer(), nullable=True),
        sa.Column("error_message", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("staged_at", sa.DateTime(), nullable=False),
        sa.Column("pushed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["anchor_link_pk"],
            ["revisionlink.pk"],
        ),
        sa.ForeignKeyConstraint(
            ["batch_pk"],
            ["promotionbatch.pk"],
        ),
        sa.ForeignKeyConstraint(
            ["page_link_pk"],
            ["pagelink.pk"],
        ),
        sa.ForeignKeyConstraint(
            ["predecessor_promotion_pk"],
            ["promotion.pk"],
        ),
        sa.ForeignKeyConstraint(
            ["source_page_pk"],
            ["page.pk"],
        ),
        sa.ForeignKeyConstraint(
            ["source_revision_pk"],
            ["revision.pk"],
        ),
        sa.ForeignKeyConstraint(
            ["target_page_pk"],
            ["page.pk"],
        ),
        sa.PrimaryKeyConstraint("pk"),
    )
    with op.batch_alter_table("promotion", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_promotion_anchor_link_pk"), ["anchor_link_pk"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_promotion_batch_pk"), ["batch_pk"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_promotion_page_link_pk"), ["page_link_pk"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_promotion_predecessor_promotion_pk"),
            ["predecessor_promotion_pk"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_promotion_source_page_pk"), ["source_page_pk"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_promotion_status"), ["status"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_promotion_target_page_pk"), ["target_page_pk"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("promotion", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_promotion_target_page_pk"))
        batch_op.drop_index(batch_op.f("ix_promotion_status"))
        batch_op.drop_index(batch_op.f("ix_promotion_source_page_pk"))
        batch_op.drop_index(batch_op.f("ix_promotion_predecessor_promotion_pk"))
        batch_op.drop_index(batch_op.f("ix_promotion_page_link_pk"))
        batch_op.drop_index(batch_op.f("ix_promotion_batch_pk"))
        batch_op.drop_index(batch_op.f("ix_promotion_anchor_link_pk"))

    op.drop_table("promotion")
    with op.batch_alter_table("slot", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_slot_content_pk"))

    op.drop_table("slot")
    op.execute(sa.text("DROP INDEX IF EXISTS uq_revisionlink_pair"))
    with op.batch_alter_table("revisionlink", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_revisionlink_remote_revision_pk"))
        batch_op.drop_index(batch_op.f("ix_revisionlink_page_link_pk"))
        batch_op.drop_index(batch_op.f("ix_revisionlink_local_revision_pk"))

    op.drop_table("revisionlink")
    with op.batch_alter_table("transclusion", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_transclusion_index_title"))

    op.drop_table("transclusion")
    with op.batch_alter_table("texttargetanchor", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_texttargetanchor_page_pk"))
        batch_op.drop_index(batch_op.f("ix_texttargetanchor_annotation_id"))

    op.drop_table("texttargetanchor")
    with op.batch_alter_table("scanannotation", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_scanannotation_page_pk"))
        batch_op.drop_index(batch_op.f("ix_scanannotation_annotation_id"))

    op.drop_table("scanannotation")
    with op.batch_alter_table("revision", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_revision_revid"))
        batch_op.drop_index(batch_op.f("ix_revision_page_pk"))

    op.drop_table("revision")
    with op.batch_alter_table("proofreadpagemeta", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_proofreadpagemeta_index_page_pk"))

    op.drop_table("proofreadpagemeta")
    with op.batch_alter_table("indexmeta", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_indexmeta_site_pk"))
        batch_op.drop_index(batch_op.f("ix_indexmeta_page_pk"))

    op.drop_table("indexmeta")
    with op.batch_alter_table("filemeta", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_filemeta_page_pk"))

    op.drop_table("filemeta")
    with op.batch_alter_table("fileblob", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_fileblob_page_pk"))

    op.drop_table("fileblob")
    with op.batch_alter_table("editjournal", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_editjournal_page_pk"))
        batch_op.drop_index(batch_op.f("ix_editjournal_committed"))

    op.drop_table("editjournal")
    with op.batch_alter_table("commit", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_commit_status"))
        batch_op.drop_index(batch_op.f("ix_commit_page_pk"))

    op.drop_table("commit")
    with op.batch_alter_table("boxrangelink", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_boxrangelink_range_annotation_id"))
        batch_op.drop_index(batch_op.f("ix_boxrangelink_page_pk"))
        batch_op.drop_index(batch_op.f("ix_boxrangelink_box_annotation_id"))

    op.drop_table("boxrangelink")
    op.drop_table("sitecredential")
    with op.batch_alter_table("promotionbatch", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_promotionbatch_target_site_pk"))
        batch_op.drop_index(batch_op.f("ix_promotionbatch_status"))
        batch_op.drop_index(batch_op.f("ix_promotionbatch_source_site_pk"))
        batch_op.drop_index(batch_op.f("ix_promotionbatch_index_link_pk"))

    op.drop_table("promotionbatch")
    with op.batch_alter_table("page", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_page_dirty"))

    op.drop_table("page")
    op.drop_table("namespace")
    with op.batch_alter_table("fetchrequest", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_fetchrequest_status"))

    op.drop_table("fetchrequest")
    op.drop_table("site")
    op.execute(sa.text("DROP INDEX IF EXISTS uq_pagelink_pair"))
    with op.batch_alter_table("pagelink", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_pagelink_remote_page_pk"))
        batch_op.drop_index(batch_op.f("ix_pagelink_local_page_pk"))
        batch_op.drop_index(batch_op.f("ix_pagelink_index_link_pk"))

    op.drop_table("pagelink")
    with op.batch_alter_table("ocrbackendconfig", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ocrbackendconfig_scope"))

    op.drop_table("ocrbackendconfig")
    with op.batch_alter_table("indexlink", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_indexlink_page_link_pk"))

    op.drop_table("indexlink")
    with op.batch_alter_table("content", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_content_content_sha1"))
        batch_op.drop_index(batch_op.f("ix_content_comparable_sha1"))

    op.drop_table("content")
    # ### end Alembic commands ###
