"""remove naive datatime

Revision ID: cddd162bf081
Revises: b72e8c913a04
Create Date: 2026-09-23 13:09:25.180297+00:00
"""

from collections.abc import Sequence

revision: str = "cddd162bf081"
down_revision: str | None = "b72e8c913a04"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    ### commands auto generated by Alembic - please adjust! ###
    pass

    #
    # with op.batch_alter_table('pagelink', schema=None) as batch_op:
    #     batch_op.create_foreign_key(
    #         "index_link_pk",
    #         "indexlink",
    #         ["index_link_pk"],
    #         ["pk"],
    #     )
    #
    # with op.batch_alter_table('revisionlink', schema=None) as batch_op:
    #     batch_op.create_foreign_key(
    #         None,
    #         "pagelink",
    #         ["page_link_pk"],
    #         ["pk"],
    #     )
    #
    # with op.batch_alter_table('site', schema=None) as batch_op:
    #     batch_op.drop_index(batch_op.f('uq_site_label'))
    #     batch_op.create_unique_constraint('uq_site_label', ['label'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass

    # with op.batch_alter_table('site', schema=None) as batch_op:
    #     batch_op.drop_constraint('uq_site_label', type_='unique')
    #     batch_op.create_index(batch_op.f('uq_site_label'), ['label'], unique=1)
    #
    # # with op.batch_alter_table('revisionlink', schema=None) as batch_op:
    # #     batch_op.drop_constraint(None, type_='foreignkey')
    #
    # with op.batch_alter_table('promotionbatch', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('approved_at', sa.DATETIME(), nullable=True))
    #     batch_op.add_column(sa.Column('approved_by', sa.VARCHAR(), nullable=True))

    # with op.batch_alter_table('pagelink', schema=None) as batch_op:
    #     batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
